title:              Fay's Blog
email:              your-email@example.com
description:        My ramblings & ruminations on machine learning, deep learning, and quant analysis of crypto/stocks.
author:             Faisal Ghaffar
baseurl:            ""
url:                "https://fghaffar.github.io"

# Social Profiles
twitter_username:   ghaffar_faisal
github_username:    fghaffar
#facebook_username:  StartBootstrap
#instagram_username:  
linkedin_username: faisal-ghaffar-15202118

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
